--- Creacion de base de datos
CREATE DATABASE NOVICOMPUT
ON (NAME='NOVICOMPUT',FILENAME='/var/opt/mssql/data/NOVICOMPUT.mdf', SIZE=10MB, MAXSIZE=20MB,FILEGROWTH=1MB)
LOG ON (NAME='NOVICOMPUT_LOG', FILENAME='/var/opt/mssql/data/NOVICOMPUT.ldf');

---Creacion de Tablas---
CREATE TABLE PRODUCTO
(
    IDPRODUCTO INT PRIMARY KEY IDENTITY,
    IDCATEGORIA INT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    STOCK INT NOT NULL,
    ACTIVO BIT NOT NULL
)

CREATE TABLE PRODUCTODETALLE
(
    IDPRODUCTODETALLE INT PRIMARY KEY,
    IDPRODUCTO INT NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL
)

